"""create bills table

Revision ID: af2467088866
Revises: 257ecec2dbb5
Create Date: 2022-06-27 13:28:17.839834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af2467088866'
down_revision = '257ecec2dbb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_bills', 'users',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_bills', 'bills',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_bills', 'bills',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_bills', 'users',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
